import type { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
	title: "Users",
	description: "Generated by create next app",
};
const Layout = async ({ children }: { children: ReactNode }) => {
	return <>{children}</>;
};

export default Layout;
